spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bahmni_avni
    driverClassName: org.postgresql.Driver
    username: bahmni_avni_admin
    password: password
  flyway:
    enabled: true
    check-location: false
    locations: classpath:db.migration