spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${INT_DB_NAME:dummy}
    driverClassName: org.postgresql.Driver
    username: bahmni_avni_admin
    password: password
  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/migration